### ISSUE TITLE
Get the X-Robots-Tag header working

### ISSUE THREAD

**Issue by simonw** [simonw/robots-txt-demos#1]
https://robots-txt-demos.now.sh/disallowed-x-robots

This should have the `X-Robots-Tag` header in it, but it doesn't:
```
$ curl -i https://robots-txt-demos.now.sh/disallowed-x-robots
HTTP/2 200 
date: Thu, 26 Jul 2018 17:18:26 GMT
content-type: text/html; charset=utf-8
set-cookie: __cfduid=d5219dd0a6d66224e94eaf529ce684c311532625506; expires=Fri, 26-Jul-19 17:18:26 GMT; path=/; domain=.robots-txt-demos.now.sh; HttpOnly
last-modified: Thu, 26 Jul 2018 17:17:20 GMT
content-disposition: inline; filename="disallowed-x-robots.html"
etag: W/"2ef22f43d363341f066a80ef05bd68297f8f8792"
cache-control: s-maxage=86400
x-now-trace: sfo1
now: 1
x-now-cache: MISS
x-now-id: 3d9q1-1532625460599-6JqO7eshbfsCNDEIMHZNXprG
cf-cache-status: HIT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 44088685bd696c4c-SJC

<h1>Disallowed</h1>
```

The configuration that is meant to turn this in is in the `now.json` file but it's not working for some reason:

https://github.com/simonw/robots-txt-demos/blob/0ef8264d897cbc6b26959dd98ce2360893fe0de3/now.json#L3-L12

**Comment by matheuss** [comment]
It looks like it's an issue with the `.html` stripping. I just changed the `source` key in `now.json` to `disallowed-x-robots.html` and it returns the header correctly:

```
▲ robots-txt-demos at master ✖ curl -sI https://robots-txt-demos-jmluuveejz.now.sh/disallowed-x-robots | grep noindex
x-robots-tag: noindex
▲ robots-txt-demos at master ✖
```

However, it doesn't return it if i add `.html` to the request: 
```
▲ robots-txt-demos at master ✖ curl -sI https://robots-txt-demos-jmluuveejz.now.sh/disallowed-x-robots.html | grep noindex
▲ robots-txt-demos at master ✖
```

On your original deployment, it doesn't return the header regardless of the request having `.html`.

@simonw for now I'll ask you to use `.html` on `now.json` so it partially works – @leo will take a deeper look at this ASAP 👌

**Comment by simonw** [comment]
@matheuss thanks for the information - I've not managed to get it working though, could you share the exact `now.json` you used? This is what I just tried:

https://github.com/simonw/robots-txt-demos/blob/7a830749c3ada815b89e5e1336998c55999c4c5b/now.json#L1-L16

**Comment by leo** [comment]
@simonw I just deployed your repository to do a few tests and it turns out that everything is actually working as expected.

The reason why @matheuss didn't get the header in his second request in the commend he shared above is because the response for accessing a path that ends with `.html` is a 301 redirection to the path without the extension (because `cleanUrls` is enabled by default).

**Long story short:**

The `source` attribute always contains the name of the actual source file you wish to apply headers to, regardless of any rewrites applied by `rewrites` or `cleanUrls`.

In turn, your config needs to look like this (notice the file extension):

```
{
    "static": {
        "headers": [
            {
                "source": "disallowed-x-robots.html",
                "headers": [
                    {
                        "key": "X-Robots-Tag",
                        "value": "noindex"
                    }
                ]
            }
        ]
    }
}
```

I hope I was able to clarify things.

**Comment by simonw** [comment]
Thanks, got it working now:
```
robots-txt-demos $ curl -i 'https://robots-txt-demos.now.sh/disallowed-x-robots'
HTTP/2 200 
date: Fri, 27 Jul 2018 21:10:06 GMT
content-type: text/html; charset=utf-8
set-cookie: __cfduid=d68ca0e24c180dc51fa80cd5e7ac5ba151532725805; expires=Sat, 27-Jul-19 21:10:05 GMT; path=/; domain=.robots-txt-demos.now.sh; HttpOnly
last-modified: Fri, 27 Jul 2018 21:09:34 GMT
content-disposition: inline; filename="disallowed-x-robots.html"
etag: W/"2ef22f43d363341f066a80ef05bd68297f8f8792"
cache-control: s-maxage=86400
x-robots-tag: noindex
x-now-trace: sfo1
now: 1
x-now-cache: MISS
x-now-id: nkgia-1532725805912-90acDMj93nZj88LH1VoPnmj5
cf-cache-status: EXPIRED
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 4412173ec891965c-SJC

<h1>Disallowed</h1>
```
